### ISSUE TITLE
API+Auth

### ISSUE THREAD

**Issue by xUmaRix** [pritunl/pritunl#80]
I had 2 issues on pritunl

1. When a user is disabled in pritunl it still can connect to the VPN.I assume that the disabled feature is to prevent disabled user from connecting to the VPN.Can anyone clarify on this.

2. I tried to authenticate to pritunl using API Token and API secret but I always get error 401 UNAUTHORIZED.Below is the code I'm using

<?php

$BASE_URL   = "https://localhost:9700";
$API_TOKEN  = "89v5HwwCpCtVOgZgAsEplu8re7JNaxEu";
$API_SECRET = "2L2fspVfCrj1q9lwczbF9EU1gEGowXCR";

function auth_request($method, $path, $data="") {
    global $BASE_URL, $API_TOKEN, $API_SECRET;

    $auth_timestamp = strval(time());
    $auth_nonce = uniqid();
    $auth_array = array(
        $API_TOKEN,
        $auth_timestamp,
        $auth_nonce,
        strtoupper($method),
    if ($data) {
        array_push($auth_array, $data);
    }

    $auth_string = join("&", $auth_array);
    $auth_signature = base64_encode(hash_hmac(
        "sha256", $auth_string, $API_SECRET, true));
    $options = array(
        "http" => array(
            "header"  => array(
                'Content-Type: application/json',
                'Auth-Token: '.$API_TOKEN,
                'Auth-Timestamp: '.$auth_timestamp,
                'Auth-Nonce: '.$auth_nonce,
                'Auth-Signature: '.$auth_signature
            ),
            "method"  => $method,
            "content" => $data,
        ),
    );

    $context = stream_context_create($options);
    return file_get_contents($BASE_URL.$path, false, $context);
}

printf(auth_request("GET", "/status")."\n");
?>

**Comment by zachhuff386** [comment]
Disable user was fixed in commit above. The php code is missing the path in the hmac signature below is php code that will authenticate with the api.

```php
<?php

$BASE_URL   = "";
$API_TOKEN  = "";
$API_SECRET = "";

function auth_request($method, $path, $data="") {
    global $BASE_URL, $API_TOKEN, $API_SECRET;

    $auth_timestamp = strval(time());
    $auth_nonce = uniqid();
    $auth_array = array(
        $API_TOKEN,
        $auth_timestamp,
        $auth_nonce,
        strtoupper($method),
        $path,
    );
    if ($data) {
        array_push($auth_array, $data);
    }

    $auth_string = join("&", $auth_array);
    $auth_signature = base64_encode(hash_hmac(
        "sha256", $auth_string, $API_SECRET, true));
    $options = array(
        "http" => array(
            "header"  => array(
                'Content-Type: application/json',
                'Auth-Token: '.$API_TOKEN,
                'Auth-Timestamp: '.$auth_timestamp,
                'Auth-Nonce: '.$auth_nonce,
                'Auth-Signature: '.$auth_signature
            ),
            "method"  => $method,
            "content" => $data,
        ),
    );

    $context = stream_context_create($options);
    return file_get_contents($BASE_URL.$path, false, $context);
};

printf(auth_request("GET", "/status")."\n");
printf(auth_request("PUT", "/organization/6d18ab1855804e5e86121e24cd3ec0e5",
    json_encode(array(
        "name" => "test",
    ))
)."\n");

?>
```

**Comment by xUmaRix** [comment]
tested the code above still the issue persist 

PHP Warning:  file_get_contents(https://localhost:9700/status): failed to open stream: HTTP request failed! HTTP/1.1 401 UNAUTHORIZED
 in /home/ubuntu/pritunl.php on line 41

The option for changing theme is not available in setting
